name: task_tide
description: My task management app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  bot_toast: ^4.1.3
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.1
  equatable: ^2.0.7
  firebase_core: ^3.8.1
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.16
  get_it: ^8.0.3
  go_router: ^14.6.2
  http: ^1.2.2
  intl: ^0.19.0
  lottie: ^3.2.0
  path: ^1.9.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.4
  shimmer: ^3.0.0
  sqflite: ^2.4.1
  toast: ^0.3.0

dev_dependencies:
  bloc_test: ^9.1.7
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
  - assets/animations/
  - assets/img/