// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhfvHXQmdu_9vMvfEfaAO-IcdcMPWIoQM',
    appId: '1:185067285211:android:cf17858271d8821cc83afe',
    messagingSenderId: '185067285211',
    projectId: 'task-tide-65b8b',
    storageBucket: 'task-tide-65b8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaRe7DoyFQLhW-1BEYz2HCdpKyBomM0Jo',
    appId: '1:185067285211:ios:cb7dd808e373e70cc83afe',
    messagingSenderId: '185067285211',
    projectId: 'task-tide-65b8b',
    storageBucket: 'task-tide-65b8b.firebasestorage.app',
    iosBundleId: 'com.edsonsalvador.tasktide.task-tide',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_1XZMHFsQBbmyNKY1DxBri1tr3pTbYFE',
    appId: '1:185067285211:web:74404db76cdc050ec83afe',
    messagingSenderId: '185067285211',
    projectId: 'task-tide-65b8b',
    authDomain: 'task-tide-65b8b.firebaseapp.com',
    storageBucket: 'task-tide-65b8b.firebasestorage.app',
    measurementId: 'G-GDFJN5X3XG',
  );

}